TEMPLATES = [
    {
        "title": "Cyberpunk Cityscape",
        "emoji": "🌃",
        "description": "Futuristic neon-lit city with flying cars and holographic advertisements",
        "prompt": "A futuristic cyberpunk cityscape at night with neon lights, flying cars, holographic billboards, and rain-soaked streets reflecting colorful lights",
        "gradient_from": "from-blue-500/30",
        "gradient_to": "to-purple-500/30",
        "button_from": "from-blue-600",
        "button_to": "to-purple-600",
    },
    {
        "title": "Minimalist Nature",
        "emoji": "🌿",
        "description": "Clean, simple nature design with geometric elements",
        "prompt": "Minimalist nature design with geometric mountain silhouettes, simple tree shapes, and a clean color palette of greens and earth tones",
        "gradient_from": "from-green-500/30",
        "gradient_to": "to-teal-500/30",
        "button_from": "from-green-600",
        "button_to": "to-teal-600",
    },
    { 
        "title": "Abstract Art",
        "emoji": "🎨",
        "description": "Colorful abstract composition with flowing shapes",
        "prompt": "Abstract art with flowing organic shapes, vibrant colors blending together, dynamic composition with paint-like textures and modern artistic style",
        "gradient_from": "from-orange-500/30",
        "gradient_to": "to-red-500/30",
        "button_from": "from-orange-600",
        "button_to": "to-red-600",
    },
    {
        "title": "Galaxy Space",
        "emoji": "✨",
        "description": "Cosmic scene with stars, nebulas and planets",
        "prompt": "Deep space galaxy scene with colorful nebulas, bright stars, distant planets, cosmic dust clouds, and aurora-like light effects in purple and blue tones",
        "gradient_from": "from-purple-500/30",
        "gradient_to": "to-pink-500/30",
        "button_from": "from-purple-600",
        "button_to": "to-pink-600",
    },
    {
        "title": "Vintage Travel",
        "emoji": "🏔️",
        "description": "Retro travel poster style with mountains",
        "prompt": "Vintage travel poster style with mountain landscape, retro color palette, classic typography elements, and nostalgic 1950s advertising aesthetic",
        "gradient_from": "from-yellow-500/30",
        "gradient_to": "to-orange-500/30",
        "button_from": "from-yellow-600",
        "button_to": "to-orange-600",
    },
    {
        "title": "Ocean Waves",
        "emoji": "🌊",
        "description": "Peaceful ocean scene with stylized waves",
        "prompt": "Stylized ocean waves with gradient blue colors, peaceful seascape, minimalist design, flowing water patterns, and calming coastal atmosphere",
        "gradient_from": "from-cyan-500/30",
        "gradient_to": "to-blue-500/30",
        "button_from": "from-cyan-600",
        "button_to": "to-blue-600",
    },
]
